#! /usr/bin/env python3

import requests
import os
import operator

base_url = "https://portal.mhascaro.com/api"

token_url = f"{base_url}/auth/login"

payload = {
    "username": os.environ['THINGSBOARD_USERNAME'],
    "password": os.environ['THINGSBOARD_PASSWORD']
}

response = requests.post(token_url, json=payload)
token = response.json()["token"]

auth_headers = {
    "X-Authorization": f"Bearer {token}"
}

list_url = f"{base_url}/entityGroup/3c521c80-53bd-11ea-aa10-3316385c1cc2/entities?limit=100"

response = requests.get(list_url, headers=auth_headers)

parking_lots = response.json()["data"]

def get_attribute(items, name):
    for i in items:
        if(i["key"] == name):
            return i["value"]

def get_timeseries_value(timeseries, name):
    val = timeseries[name][0]["value"]
    if val == None:
        return 0
    else:
        return int(float(val))

def fetch_lot_data(lot):
    id = lot["id"]["id"]

    attribute_url = f"{base_url}/plugins/telemetry/ASSET/{id}/values/attributes?keys=address,latitude,longitude"
    attrs = requests.get(attribute_url, headers=auth_headers).json()

    timeseries_url = f"{base_url}/plugins/telemetry/ASSET/{id}/values/timeseries?keys=latestSumParkingState,SumOccupied,TotalParking_mapping"
    timeseries = requests.get(timeseries_url, headers=auth_headers).json()

    return {
        "id":               id,
        "address":          get_attribute(attrs, "address"),
        "latitude":         get_attribute(attrs, "latitude"),
        "longitude":        get_attribute(attrs, "longitude"),
        "total_spaces":     get_timeseries_value(timeseries, "TotalParking_mapping"),
        "occupied_spaces":  get_timeseries_value(timeseries, "latestSumParkingState")
    }

updated_lots = list(map(fetch_lot_data, parking_lots))
print(updated_lots)
